var PRODUCTS = [
  { id:1, name:'10% Vita-C Face Serum 30ml', category:'serums', price:299, mrp:499, badge:'Bestseller', icon:'✨', bg:'#F0E4D8', desc:'For Hyperpigmentation & Dull Skin', fullDesc:'Aqua, 3-O-Ethyl Ascorbic Acid, Butylene Glycol, Propanediol, Betaine, Citrus Limon (Lemon) Fruit Extract, Centella Asiatica Extract, Sodium PCA, Glycyrrhiza Glabra (Licorice) Root Extract, Sodium Polyacryloyldimethyl Taurate, Sodium Hyaluronate,Phenoxyethanol, Ethylhexylglycerin, Citric Acid, Allantoin, Sodium Gluconate, Fragrance.', rating:4.8, reviews:120, tags:['brightening','serum','vitamin-c'], skin:'All skin types', size:'30ml', img:'images/products/vit-c-serum.jpg' },
  { id:2, name:'Niacinamide Face Serum 30ml', category:'serum', price:299, mrp:499, badge:'Bestseller', icon:'💧', bg:'#D8E0D4', desc:'For Hyperpigmentation & Dull Skin', fullDesc:'Aqua, Niacinamide, Propanediol, Butylene Glycol, Zinc PCA, Oryza Sativa (Rice) Extract, Pentylene Glycol, 1,2-Hexanediol,Sodium Polyacryloyldimethyl Taurate, Sodium Hyaluronate, Phenoxyethanol, Ethylhexylglycerin, Betaine, Allantoin, Panthenol, Xanthan Gum, Acacia Senegal Gum, Sodium Gluconate, Citric Acid, Fragrance.', rating:4.8, reviews:80, tags:['brightening','serum','vitamin-c'], skin:'All skin types', size:'30ml', img:'images/products/hydra-cream.jpg' },
  { id:3, name:'2% Salicylic Acid Face Serum 30ml', category:'serum', price:299, mrp:499, badge:'New', icon:'💧', bg:'#D8E0D4', desc:'For Hyperpigmentation & Dull Skin', fullDesc:'Aqua, Pentylene Glycol, Salicylic Acid, Glycerin,  Glyceine Soja Seed Extract, D-Panthenol, Niacinamide, Glyceryl Caprylate,  Propylene Glycol, Salix Alba Bark Extract, Sodium PCA, Azadirachta Indica Leaf Extract, Sodium Polyacryloyldimethyl Taurate, Glycolic Acid,  Xanthan Gum, Camellia Sinensis Leaf Extract, Chamomilla Recutita (Matricaria) Flower Extract, Phenoxyethanol, Ethylhexylglycerin, Citric Acid, Sodium Benzoate, Potassium Sorbate, Sodium Gluconate, Fragrance.', rating:4.8, reviews:80, tags:['brightening','serum','vitamin-c'], skin:'All skin types', size:'30ml', img:'images/products/hydra-cream.jpg' },
  { id:4, name:'Spot Removal Face Serum 30ml', category:'serum', price:299, mrp:499, badge:'New', icon:'💧', bg:'#D8E0D4', desc:'For Hyperpigmentation & Dull Skin', fullDesc:'Aqua, Niacinamide, 3-O-Ethyl Ascorbic Acid, Butylene Glycol, Propanediol, Alpha Arbutin, Kojic Acid, 1,2-Hexanediol, Panthenol, Betaine, Centella Asiatic Extract, Morus Alba Root Extract,  Sodium Hyaluronate, Sodium PCA, Allantoin, Lactic Acid, Glycolic Acid, Glycyrrhiza Glabra Root Extract, Sodium Polyacryloyldimethyl Taurate, Phenoxyethanol, Ethylhexyglycerin, Sodium Benzoate, Potassium Sorbate, Sodium Gluconate,Citric Acid, Fragrance.', rating:4.8, reviews:80, tags:['brightening','serum','vitamin-c'], skin:'All skin types', size:'30ml', img:'images/products/hydra-cream.jpg' },
  { id:5, name:'Rosemary Hair  Serum 30ml', category:'serum', price:299, mrp:499, badge:'New', icon:'💧', bg:'#D8E0D4', desc:'For Hyperpigmentation & Dull Skin', fullDesc:'Aqua, Rosmarinus Officinalis (Rosemary) Leaf Extract, Propanediol, Ethoxydiglycol, Curcuma Longa (Turmeric) Root Extract, Betaine, Niacinamide, D-Panthenol, Pentylene Glycol, Glycerin, Hydroxyethyl Urea, Oryza Sativa (Rice) Extract, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Phenoxyethanol, Ethylhexylglycerin, Sodium Benzoate, Potassium Sorbate, Citric Acid, Sodium Gluconate, Fragrance.', rating:4.8, reviews:80, tags:['brightening','serum','vitamin-c'], skin:'All skin types', size:'30ml', img:'images/products/hydra-cream.jpg' },
  { id:29, name:'Anti Acne Face Serum 30ml', category:'serum', price:299, mrp:499, badge:'New', icon:'💧', bg:'#D8E0D4', desc:'Anti Acne Face Serum', fullDesc:'Aqua, Pentylene Glycol, Salicylic Acid, Glycerin, Glycolic Acid, Glyceine Soja Seed Extract, Glyceryl Caprylate,  Propylene Glycol, Salix Alba Bark Extract, Azadirachta Indica Leaf Extract, Sodium Polyacryloyldimethyl Taurate, Xanthan Gum, Camellia Sinensis Leaf Extract, Chamomilla Recutita (Matricaria) Flower Extract, Phenoxyethanol, Ethylhexylglycerin, Citric Acid, Sodium Benzoate, Potassium Sorbate, Sodium Gluconate, Fragrance.', rating:4.8, reviews:80, tags:['brightening','serum','vitamin-c'], skin:'All skin types', size:'30ml', img:'images/products/hydra-cream.jpg' },
  { id:30, name:'2% Alpha Arbutin Face Serum 30ml', category:'serum', price:299, mrp:499, badge:'New', icon:'💧', bg:'#D8E0D4', desc:'2% Alpha Arbutin Face Serum ', fullDesc:'Aqua, Propanediol, Alpha Arbutin, Glycerin, Butylene Glycol, Panax Ginseng Root Extract, Sodium Hyaluronate, Centella Asiatica Extract, Sodium PCA, Citrus Aurantium Dulcis (Orange) Peel Extract, Hydroxyethyl Cellulose, Sodium Polyacryloyldimethyl Taurate, Xanthan Gum, Phenoxyethanol, Ethylhexylglycerin, Sodium Benzoate, Potassium Sorbate, Sodium Gluconate, Citric Acid, Fragrance.', rating:4.8, reviews:80, tags:['brightening','serum','vitamin-c'], skin:'All skin types', size:'30ml', img:'images/products/hydra-cream.jpg' },
  { id:31, name:'Skin Brightening Face Serum 30ml', category:'serum', price:299, mrp:499, badge:'New', icon:'💧', bg:'#D8E0D4', desc:'Skin Brightening Face Serum', fullDesc:'Aqua, Niacinamide, Kojic Acid, Pentylene Glycol, Glycerin, 3-O-Ethyl Ascorbic Acid, Butylene Glycol, Alpha Arbutin, Panax Ginseng Root Extract, Glycolic Acid, Morus Alba Root Extract, Glycyrrhiza Glabra Root Extract, Sodium PCA, Sodium Polyacryloyldimethyl Taurate, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Phenoxyethanol, Ethylhexylglycerin, Sodium Benzoate, Potassium Sorbate, Xanthan Gum, Sodium Gluconate, Citric Acid, Fragrance', rating:4.8, reviews:80, tags:['brightening','serum','vitamin-c'], skin:'All skin types', size:'30ml', img:'images/products/hydra-cream.jpg' },
  { id:6, name:'Moisturizer Cream 50gm', category:'Cream', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Moisturizer Cream', fullDesc:'Aqua, Caprylic/Capric Triglyceride, Butyrospermum Parkii (Shea) Butter, Propanediol, Xylitylglucoside (and)Anhydroxylitol (and) Xylitol, Simmondsia Chinensis(Jojoba) Seed Oil, Sodium Polyacrylate (and) Dicaprylyl Carbonate (and) Polyglyceryl-3Caprate, Glyceryl Stearate (and) PEG-100 Stearate,Cetyl Alcohol, Cetearyl Olivate (and) Sorbitan Olivate, Glycerine, Squalane, Ammonium  Acryloyldimethyltaurate/VP Copolymer, Xanthan Gum,  Phenoxyethanol, Ethylhexylglycerin, Sodium Benzoate, Potassium Sorbate Citric Acid, Allantoin, Sodium Gluconate, Fragrance', skin:'All skin types', size:'50gm', img:'images/sunscreen.jpg' },
  { id:7, name:'Night Cream 50gm', category:'Cream', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Night Cream', fullDesc:'Aqua, Butylene Glycol, Butyrospermum Parkii (Shea) Butter, 1,2-Hexanediol, Cetearyl Alcohol, Cetearyl Olivate, Cetyl Ethylhexanoate, Sorbitan Olivate, Beeswax, Glycerin, Niacinamide, Glyceryl Stearate, Sodium Hyaluronate, Sodium Polyacryloyldimethyl Taurate, Tocopherol, Xylitol, Xylitylglucoside, Anhydroxylitol, Bakuchiol, Xanthan Gum,  Phenoxyethanol, Ethylhexylglycerin, Sodium Benzoate, Potassium Sorbate Citric Acid, Allantoin, Sodium Gluconate, Fragrance', skin:'All skin types', size:'50gm', img:'images/products/sunscreen.jpg' },
  { id:8, name:'Retinol Cream 50gm', category:'Cream', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Retinol Cream ', fullDesc:'Aqua, Niacinamide, Butylene Glycol, Butyrospermum Parkii (Shea) ButterHelianthus Annuus (Sunflower) Seed Oil, Aloe Barbadensis (Aloe Vera) Leaf Juice, Propanediol, Hydrolyzed Hyaluronic Acid, Cetearyl Olivate, Cetyl Ethylhexanoate, Sorbitan Olivate, Betaine, Ammonium Acryloyldimethyltaurate/VP Copolymer, Hydrolyzed Rice Protein, Glycyrrhiza Glabra (Licorice) Root Extract, Retinol, Phenoxyethanol, Ethylhexylglycerin, Sodium Benzoate, Potassium Sorbate Citric Acid, Allantoin, Sodium Gluconate, Fragrance', skin:'All skin types', size:'50gm', img:'images/products/sunscreen.jpg' },
  { id:9, name:'Skin Lightening Cream 50gm', category:'Cream', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Skin Lightening Cream  ', fullDesc:'Aqua, Butyrospermum Parkii (Shea) Butter, 1,2-Hexanediol, Cetearyl Alcohol, Cetearyl Olivate, Cetyl Ethylhexanoate, Sorbitan Olivate, Niacinamide, Kojic Acid, Pentylene Glycol, Glycerin, 3-O-Ethyl Ascorbic Acid, Butylene Glycol, Alpha Arbutin, Panax Ginseng Root Extract, Glycolic Acid, Morus Alba Root Extract, Glycyrrhiza Glabra Root Extract, Sodium PCA, Sodium Polyacryloyldimethyl Taurate, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Phenoxyethanol, Ethylhexylglycerin, Sodium Benzoate, Potassium Sorbate, Xanthan Gum, Sodium Gluconate, Citric Acid, Fragrance', skin:'All skin types', size:'50gm', img:'images/products/sunscreen.jpg' },
  { id:10, name:'SPF 30 Cream 50gm', category:'Cream', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'SPF 30 Cream ', fullDesc:'Aqua, Octyl Methoxycinnamate, C12-15 Alkyl Benzoate,Cetearyl Alcohol, Cetearyl Olivate, Sorbitan Olivate, Dicaprylyl Carbonate, Octocrylene, Butyl Methoxydibenzoylmethane, Betaine,  Propanediol, Glycerine, Sodium Ascorbyl Phosphate, Sodium Hyaluronate, Tocopheryl Acetate, D-Panthenol, Allantoin, Acrylate/ Sodium Acryloyldimethyl Taurate Copolymer, Caprylic/Capric Triglyceride, Aloe Barbadensis Leaf Extract, Citrus Reticulata (Tangerine) Fruit Extract, Sodium Hydroxide, Phenoxyethanol, Ethylhexylglycerin, Sodium Benzoate, Potassium Sorbate, Xanthan Gum, Sodium Gluconate, Citric Acid, Fragrance', skin:'All skin types', size:'50gm', img:'images/products/sunscreen.jpg' },
  { id:11, name:'Ubtan Cream 50gm', category:'Cream', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Ubtan Cream  ', fullDesc:'Aqua, Butyrospermum Parkii (Shea) Butter, 1,2-Hexanediol, Cetearyl Alcohol, Cetearyl Olivate, Cetyl Ethylhexanoate, Crocus Sativus Flower Extract, Sorbitan Olivate, Niacinamide, Kojic Acid, Pentylene Glycol, Glycerin, 3-O-Ethyl Ascorbic Acid, Butylene Glycol, Alpha Arbutin, Panax Ginseng Root Extract, Glycolic Acid, Curcuma Longa (Turmeric) Root Extract, Glycyrrhiza Glabra Root Extract, Sodium PCA, Sodium Polyacryloyldimethyl Taurate, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Phenoxyethanol, Ethylhexylglycerin, Sodium Benzoate, Potassium Sorbate, Xanthan Gum, Sodium Gluconate, Citric Acid, Fragrance', skin:'All skin types', size:'50gm', img:'images/products/sunscreen.jpg' },
  { id:12, name:'Sunscreen SPF 50 ', category:'Commodity Product', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Sunscreen SPF 50', fullDesc:'Aqua, Octyl Methoxycinnamate, C12-15 Alkyl Benzoate,Cetearyl Alcohol, Cetearyl Olivate, Sorbitan Olivate, Dicaprylyl Carbonate, Octocrylene, Methylene Bis-benzotriazolyl Tetramethylbutylphenol, Butyl Methoxydibenzoylmethane, Bis-ethylhexyloxyphenol Methoxyphenyl Triazine, Betaine,  Propanediol, Glycerine, Sodium Ascorbyl Phosphate, Sodium Hyaluronate, Tocopheryl Acetate, D-Panthenol, Allantoin, Acrylate/ Sodium Acryloyldimethyl Taurate Copolymer, Caprylic/Capric Triglyceride, Aloe Barbadensis Leaf Extract, Citrus Reticulata (Tangerine) Fruit Extract, Sodium Hydroxide, Phenoxyethanol, Ethylhexylglycerin, Sodium Benzoate, Potassium Sorbate, Xanthan Gum, Sodium Gluconate, Citric Acid, Fragrance', skin:'All skin types', size:'50gm', img:'images/products/sunscreen.jpg' },
  { id:13, name:'Kojic Acid Cream', category:'Commodity Product', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Kojic Acid Cream', fullDesc:'Aqua, Butyrospermum Parkii (Shea) Butter, 1,2-Hexanediol, Kojic Acid Dipalmitate, Acetyl Glucosamine, Cetearyl Alcohol, Cetearyl Olivate, Cetyl Ethylhexanoate, Crocus Sativus Flower Extract, Sorbitan Olivate, Niacinamide, Pentylene Glycol, Glycerin, 3-O-Ethyl Ascorbic Acid, Butylene Glycol, Alpha Arbutin, Panax Ginseng Root Extract, Glycolic Acid, Curcuma Longa (Turmeric) Root Extract, Glycyrrhiza Glabra Root Extract, Sodium PCA, Sodium Polyacryloyldimethyl Taurate, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Potassium Cetyl Phosphate, Phenoxyethanol, Ethylhexylglycerin, Sodium Benzoate, Potassium Sorbate, Xanthan Gum, Sodium Gluconate, Citric Acid, Fragrance', skin:'All skin types', size:'50gm', img:'images/products/sunscreen.jpg' },
  { id:14, name:'Wax Powder', category:'Commodity Product', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Wax Powder', fullDesc:'Bentonite, Starch, Urea, Calcium hydroxide, Thiglycoic Acid, Kaolin, Fragrance, Sandalwood oil, Kesar oil', skin:'All skin types', size:'50gm', img:'images/products/sunscreen.jpg' },
  { id:15, name:'Rosemary Conditioner', category:'Conditioner', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Rosemary Conditioner', fullDesc:'Aqua, Cetostearyl Alochol, Cetyl Alochol, Cetrimonium Chloride, Glycerine, Helianthus Annuus (Sunflower) Seed Oil, Caprylic/Carpric Triglyceride, Behentrimonium Chloride, Cyclopentasiloxane, Dimethiconol, Amodimethicone, Rosmarinus Officinalis (Rosemary) Extract, Trigonella Foenum Graecum (Fenugreek) Extract, Guar Hydroxypropyl Trimonium Chloride, Trehalose, Hydrolysed Keratin, Polyquaternium-37, Polyquaternium-7, Butyrospermum Parkii (Shea) Butter, Propanediol, Polyquaternium-10, Phenoxyethanol, Ethylhexylglycerin, Sodium Benzoate, Potassium Sorbate, Xanthan Gum, Sodium Gluconate, Citric Acid, Fragrance', skin:'All skin types', size:'30ml', img:'images/products/sunscreen.jpg' },
  { id:16, name:'Rice Water Conditioner', category:'Conditioner', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Rice Water Conditioner', fullDesc:'Aqua, Cetostearyl Alochol, Cetyl Alochol, Cetrimonium Chloride, Glycerine, Oryza Sativa (Rice) Water Extract, Helianthus Annuus (Sunflower) Seed Oil, Caprylic/Carpric Triglyceride, Behentrimonium Chloride, Cyclopentasiloxane, Dimethiconol, Amodimethicone, Rosmarinus Officinalis (Rosemary) Extract, Trigonella Foenum Graecum (Fenugreek) Extract, Guar Hydroxypropyl Trimonium Chloride, Trehalose, Hydrolysed Keratin, Polyquaternium-37, Polyquaternium-7, Butyrospermum Parkii (Shea) Butter, Propanediol, Polyquaternium-10, Phenoxyethanol, Ethylhexylglycerin, Sodium Benzoate, Potassium Sorbate, Xanthan Gum, Sodium Gluconate, Citric Acid, Fragrance', skin:'All skin types', size:'30ml', img:'images/products/sunscreen.jpg' },
  { id:17, name:'Anti Dandruff Conditioner', category:'Conditioner', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Anti Dandruff Conditioner', fullDesc:'Aqua, Cetostearyl Alochol, Cetyl Alochol, Cetrimonium Chloride, Glycerine, Azadirachta Indica Leaf Extract, Helianthus Annuus (Sunflower) Seed Oil, Caprylic/Carpric Triglyceride, Behentrimonium Chloride, Cyclopentasiloxane, Dimethiconol, Amodimethicone, Rosmarinus Officinalis (Rosemary) Extract, Salicylic Acid, Guar Hydroxypropyl Trimonium Chloride, Trehalose, Hydrolysed Keratin, Polyquaternium-37, Polyquaternium-7, Butyrospermum Parkii (Shea) Butter, Propanediol, Polyquaternium-10, Phenoxyethanol, Ethylhexylglycerin, Sodium Benzoate, Potassium Sorbate, Xanthan Gum, Sodium Gluconate, Citric Acid, Fragrance', skin:'All skin types', size:'30ml', img:'images/products/sunscreen.jpg' },
  { id:18, name:'Damage Repair Conditioner', category:'Conditioner', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Damage Repair Conditioner', fullDesc:'Aqua, Cetostearyl Alochol, Cetyl Alochol, Cetrimonium Chloride, Glycerine, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Helianthus Annuus (Sunflower) Seed Oil, Caprylic/Carpric Triglyceride, Behentrimonium Chloride, D-Panthenol, Niacinamide, Hydrolysed Wheat Protein, Cyclopentasiloxane, Dimethiconol, Amodimethicone, Argania Spinosa Kernel Oil, Guar Hydroxypropyl Trimonium Chloride, Trehalose, Hydrolysed Keratin, Polyquaternium-37, Polyquaternium-7, Butyrospermum Parkii (Shea) Butter, Propanediol, Polyquaternium-10, Phenoxyethanol, Ethylhexylglycerin, Sodium Benzoate, Potassium Sorbate, Xanthan Gum, Sodium Gluconate, Citric Acid, Fragrance', skin:'All skin types', size:'30ml', img:'images/products/sunscreen.jpg' },
  { id:19, name:'7 in 1 Repair Conditioner', category:'Conditioner', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'7 in 1 Repair Conditioner', fullDesc:'Aqua, Nigella Sativa Seed Oil, Cetostearyl Alochol, Cetyl Alochol, Cetrimonium Chloride, Glycerine, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Helianthus Annuus (Sunflower) Seed Oil, Caprylic/Carpric Triglyceride, Behentrimonium Chloride, D-Panthenol, Niacinamide, Hydrolysed Wheat Protein, Cyclopentasiloxane, Dimethiconol, Amodimethicone, Argania Spinosa Kernel Oil, Guar Hydroxypropyl Trimonium Chloride, Trehalose, Hydrolysed Keratin, Polyquaternium-37, Polyquaternium-7, Butyrospermum Parkii (Shea) Butter, Propanediol, Polyquaternium-10, Phenoxyethanol, Ethylhexylglycerin, Sodium Benzoate, Potassium Sorbate, Xanthan Gum, Sodium Gluconate, Citric Acid, Fragrance', skin:'All skin types', size:'30ml', img:'images/products/sunscreen.jpg' },
  { id:20, name:'Salicylic Acid Face Wash (With Applicator)', category:'Face Wash', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Salicylic Acid Face Wash', fullDesc:'Aqua, Sodium Lauroyl Sarcosinat, Disodium Cocoamphodiacetate, Cocamidopropyl Betaine, Decyl Glucoside, Glycerin, Sodium Methyl Cocoyl Taurate, Salicylic Acid, Xylitylglucoside, Anhydroxyxylitol, Xylitol, Glucose, Anhydroxylitol, Betaine, Witch Hazel Extract, Propylene Glycol, Olea Europaea Fruit Extract, Willow Bark Extract, Panthenol, Xylitylglucoside, Glycyrrhiza Glabra (Licorice) Extract, Saccharide Isomerate, Sodium Citrate, Salix Alba Extract, Phenoxyethanol, Ethylhexylglycerin, Sodium Benzoate, Potassium Sorbate Citric Acid, Allantoin, Sodium Gluconate, Fragrance', skin:'All skin types', size:'30ml', img:'images/products/sunscreen.jpg' },
  { id:21, name:'Skin Brightening Face Wash (With Applicator)', category:'Face Wash', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Skin Brightening Face Wash', fullDesc:'Aqua, Cocoamidopropyl Betaine, Sodium Lauryl Sarcosinate, Decyl Glucoside,  Xylitylglucoside, Anhydroxyxylitol, Terminalia Ferdinandiana (Kakadu Plum) Fruit Extract, Citrus Reticulata (Tangerine) Fruit Extract, Sodium Ascorbyl Phosphate, Terminalia Ferdinandiana Fruit Extract, Sodium PCA, Niacinamide, Phenoxyethanol, Ethylhexylglycerin, Sodium Benzoate, Postassium Sorbate, Citric Acid, Sodium Gluconate, Fragrance.', skin:'All skin types', size:'30ml', img:'images/products/sunscreen.jpg' },
  { id:22, name:'Green Tea Face Wash (With Applicator)', category:'Face Wash', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Green Tea Face Wash', fullDesc:'Aqua, Sodium Lauryl Sarcosinate, Propanediol, Cocoamidopropyl Betaine, Glycerine, Cocamide MEA, Camellia Sinensis (Green Tea) Leaf Extract,  Xylitylglucoside, Anhydroxyxylitol, Glycolic Acid, Lactic Acid, Polyquaternium-39, Betaine, D-Panthenol, Niacinamide, Allantoin, Phenoxyethanol, Ethylhexylglycerin, Citric Acid, Sodium Benzoate, Potassium Sorbate, Sodium Gluconate, Fragrance.', skin:'All skin types', size:'30ml', img:'images/products/sunscreen.jpg' },
  { id:23, name:'Salicylic Acid Face Wash 100ml', category:'Face Wash', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Salicylic Acid Face Wash', fullDesc:'Aqua, Sodium Lauroyl Sarcosinate, Acrylates Copolymer, Disodium Cocoamphodiacetate, Cocamidopropyl Betaine, Decyl Glucoside, Glycerin, Sodium Methyl Cocoyl Taurate, Salicylic Acid, Sodium Hydroxide, Xylitol, Glucose, Anhydroxylitol, Betaine, Witch Hazel Extract, Propylene Glycol, Olea Europaea Fruit Extract, Willow Bark Extract, Panthenol, Xylitylglucoside, Glycyrrhiza Glabra (Licorice) Extract, Saccharide Isomerate, Phenoxyethanol, Ethylhexylglycerin, Citric Acid, Sodium Citrate, Salix Alba Extract, Sodium Benzoate, Potassium Sorbate, Allantoin, Sodium Gluconate, Fragrance', skin:'All skin types', size:'30ml', img:'images/products/sunscreen.jpg' },
  { id:24, name:'Skin Brightening Face Wash 100ml', category:'Face Wash', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Skin Brightening Face Wash', fullDesc:'Aqua, Cocoamidopropyl Betaine, Sodium Lauryl Sarcosinate, Decyl Glucoside, Acrylates Copolymer, Terminalia Ferdinandiana (Kakadu Plum) Fruit Extract, Citrus Reticulata (Tangerine) Fruit Extract, Sodium Ascorbyl Phosphate, Terminalia Ferdinandiana Fruit Extract, Sodium PCA, Sodium Hydroxide, Niacinamide, Phenoxyethanol, Ethylhexylglycerin, Sodium Benzoate, Postassium Sorbate, Citric Acid, Sodium Gluconate, Fragrance.', skin:'All skin types', size:'30ml', img:'images/products/sunscreen.jpg' },
  { id:25, name:'Green Tea Face Wash 100ml', category:'Face Wash', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Green Tea Face Wash', fullDesc:'Aqua, Acrylates Copolymer, Sodium Laureth Sulphate, Propanediol, Cocoamidopropyl Betaine, Glycerine, Cocamide MEA, Camellia Sinensis (Green Tea) Leaf Extract, Glycolic Acid, Sodium Hydroxide, Polyquaternium-39, Betaine, D-Panthenol, Niacinamide, Allantoin, Phenoxyethanol, Ethylhexylglycerin, Citric Acid, Sodium Benzoate, Potassium Sorbate, Sodium Gluconate, Fragrance.', skin:'All skin types', size:'30ml', img:'images/products/sunscreen.jpg' },
  { id:26, name:'Rosemary Shampoo 200ml', category:'Shampoo', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Rosemary Shampoo', fullDesc:'Aqua, Sodium Lauryl Sarcosinate, Cocoamidopropyl Betaine, Acrylates Copolymer, Sodium Cocyl Isethionate, Glycerin, Coco-Glucoside, Lauryl Glucoside, Polyquaternium -22, Dimethicone, Sodium Cocyl Glycinate, Rosmarinus Officinalis (Rosemary) Leaf Extract, Laureth-4, Hydroxypropyl Trimonium Chloride, Polyquaternium-39, Oryza Sativa (Rice) Extract, Hydrolyzed Wheat Protein, Sodium Hydroxide, Sodium Gluconate, Curcuma Longa(Turmeric) Root Extract, Phenoxyethanol, Ethylhexylglycerin, Citric Acid, Fragrance.', skin:'All skin types', size:'30ml', img:'images/products/sunscreen.jpg' },
  { id:27, name:'Rice Water Shampoo 200ml', category:'Shampoo', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Rice Water Shampoo ', fullDesc:'Aqua, Oryza Sativa(Rot) Water, Cocoamidopropyl Betaine, Sodium Lauryl Sarcosinate, Sodium Methyl Cocyl Taurate, Glycerin, Acrylate Copolymer, Propanediol, Cocamide MEA, Betaine, Niacinamide, Polyquaternium-10, D-Panthenol, Guar Hydroxypropyl Trimonium Chloride, Allantoin, Hydrolyzed Keratin, Hydrolyzed Wheat Protein, Polyquaternium-37, Rosmarinus Officinalis (Rosemary) Leaf Extract, Sodium Hydroxide,  Phenoxyethanol, Ethylhexylglycerin, Sodium Benzoate, Potassium Sorbate, Citric Acid, Sodium Gluconate, Fragrance.', skin:'All skin types', size:'30ml', img:'images/products/sunscreen.jpg' },
  { id:28, name:'Anti Dandruff Shampoo 200ml', category:'Shampoo', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Anti Dandruff Shampoo', fullDesc:'Aqua, Sodium Laureth Sulphate, Cocamidopropyl Betaine, Acrylates Copolymer, C14-16 Olefin Sulfonate, Sodium Cocyl Isethionate, Rosmarinus Officinalis (Rosemary) Leaf Extract, Sodium Cocyl Glycinate, Polyquaternium-37, Polyquaternium-7, Propylene Glycol, Salicylic Acid, Glycolic Acid, Piroctone Olamine, Sodium PCA, Phenoxyethanol, Ethylhexylglycerin, Fragrance, Guar Hydroxypropyltrimonium Chloride, Niacinamide, Xylitol, Sodium Hydroxide, Disodium EDTA, Citric Acid, Potassium Sorbate, Sodium Benzoate, Fragrance', skin:'All skin types', size:'30ml', img:'images/products/sunscreen.jpg' },
  { id:29, name:'Damage Repair Shampoo 200ml', category:'Shampoo', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Damage Repair Shampoo ', fullDesc:'Aqua, Linum Usitatissimum (Linseed) Seed Extract, Sodium Lauroyl Sarcosinate, Cocamidopropyl Betaine, Cocamide Mea, Disodium Cocoamphodiacetate, Sodium Cocoyl Isethionate, Polyquaternium-37, Sodium Methyl Cocyl Taurate, Sodium Cocyl Glycinate, Polyquaternium-44, Ceramide Eop, Ceramide NS, Ceramide NP, Ceteareth-60, Acrylates Copolymer, Guar Hydroxypropyl Trimonium Chloride, Xylitylglucoside, Anhydroxyxylitol, Sodium Hydroxide, Camellia Sinensis Leaf Extract, Phenoxyethanol, Ethylhexylglycerin, Citric Aid, Sodium Gluconate, Fragrance.', skin:'All skin types', size:'30ml', img:'images/products/sunscreen.jpg' },
  { id:30, name:'7 in 1 Repair Shampoo 200ml', category:'Shampoo', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'7 in 1 Repair Shampoo', fullDesc:'Aqua, Sodium Lauryl Sarcosinate, Sodium Cocyl Isethionate, Cocoamidopropyl Betaine, Propanediol, Glycerine, Pisum Sativum (Pea) Extract, Xylitylglucoside, Anhydroxylitol, Hydrolyzed Wheat Protein, Polquaternium-6, Polquaternium-10, Guar Hydroxypropyl Trimonium Chloride, Trigonella Foenum-Graexum (Fenugreek) Extract, Aloe Barbadensis Leaf Extract, Acrylates Copolymer, D-Panthenol, Betaine, Niacinamide, Biotin, Allantoin, Glycolic Acid, Citric Acid, Phenoxyethanol, Ethylhexyl Glycerin, Sodium Benzoate, Potassium Sorbate, Sodium Hydroxide, Sodium Gluconate, Fragrance.', skin:'All skin types', size:'200ml', img:'images/products/sunscreen.jpg' },
  { id:28, name:'Anti Dandruff Shampoo 200ml', category:'Shampoo', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Anti Dandruff Shampoo', fullDesc:'Aqua, Sodium Laureth Sulphate, Cocamidopropyl Betaine, Acrylates Copolymer, C14-16 Olefin Sulfonate, Sodium Cocyl Isethionate, Rosmarinus Officinalis (Rosemary) Leaf Extract, Sodium Cocyl Glycinate, Polyquaternium-37, Polyquaternium-7, Propylene Glycol, Salicylic Acid, Glycolic Acid, Piroctone Olamine, Sodium PCA, Phenoxyethanol, Ethylhexylglycerin, Fragrance, Guar Hydroxypropyltrimonium Chloride, Niacinamide, Xylitol, Sodium Hydroxide, Disodium EDTA, Citric Acid, Potassium Sorbate, Sodium Benzoate, Fragrance', skin:'All skin types', size:'30ml', img:'images/products/sunscreen.jpg' },
  { id:28, name:'Anti Dandruff Shampoo 200ml', category:'Shampoo', price:299, mrp:499, badge:'', icon:'🌤️', bg:'#F0E8D8', desc:'Anti Dandruff Shampoo', fullDesc:'Aqua, Sodium Laureth Sulphate, Cocamidopropyl Betaine, Acrylates Copolymer, C14-16 Olefin Sulfonate, Sodium Cocyl Isethionate, Rosmarinus Officinalis (Rosemary) Leaf Extract, Sodium Cocyl Glycinate, Polyquaternium-37, Polyquaternium-7, Propylene Glycol, Salicylic Acid, Glycolic Acid, Piroctone Olamine, Sodium PCA, Phenoxyethanol, Ethylhexylglycerin, Fragrance, Guar Hydroxypropyltrimonium Chloride, Niacinamide, Xylitol, Sodium Hydroxide, Disodium EDTA, Citric Acid, Potassium Sorbate, Sodium Benzoate, Fragrance', skin:'All skin types', size:'30ml', img:'images/products/sunscreen.jpg' },

];

var BLOG_POSTS = [
  { id:1, title:'The Ultimate Guide to Layering Serums', cat:'Skincare Tips', date:'12 May 2026', icon:'📖', excerpt:'Learn the correct order to layer your serums for maximum absorption and effectiveness.' },
  { id:2, title:'Why Bakuchiol is the Future of Anti-Ageing', cat:'Ingredients', date:'5 May 2026', icon:'🌿', excerpt:'Bakuchiol delivers retinol-like results without the irritation, dryness, or sun sensitivity.' },
  { id:3, title:'Building a Routine for Indian Skin in Summer', cat:'Routines', date:'28 Apr 2026', icon:'☀️', excerpt:'Summer in India means heat, humidity, and pollution. Here\'s how to adapt your skincare routine.' },
  { id:4, title:'Decoding Niacinamide: Everything You Need to Know', cat:'Ingredients', date:'20 Apr 2026', icon:'🔬', excerpt:'Niacinamide does it all — minimises pores, brightens, repairs the barrier, and reduces inflammation.' }
];

var ROUTINES = [
  { title:'Morning Routine', icon:'🌅', subtitle:'Protect & Brighten', steps:['Cleanse','Tone','Serum','Moisturise','Protect'] },
  { title:'Evening Routine', icon:'🌙', subtitle:'Repair & Restore', steps:['Double Cleanse','Tone','Treatment','Eye Care','Moisturise'] }
];

var INGREDIENTS_DATA = [
  { name:'Bakuchiol', icon:'🌸', benefit:'Anti-ageing', origin:'Babchi plant', desc:'Clinically proven to reduce fine lines and improve skin firmness as effectively as retinol, without irritation.', tags:['Anti-ageing','Firming'] },
  { name:'Rose Hip Oil', icon:'🌹', benefit:'Brightening', origin:'Chile & Argentina', desc:'Packed with vitamin A, vitamin C, and essential fatty acids. Fades scars and hyperpigmentation.', tags:['Brightening','Scars'] },
  { name:'Hyaluronic Acid', icon:'💧', benefit:'Hydration', origin:'Fermentation', desc:'Holds 1000x its weight in water. Provides 72-hour moisture at all skin layers.', tags:['Hydration','Plumping'] },
  { name:'Vitamin C', icon:'☀️', benefit:'Brightening', origin:'Plant-derived', desc:'Stabilised 15% ascorbic acid brightens dark spots, evens skin tone, and provides antioxidant protection.', tags:['Brightening','Antioxidant'] },
  { name:'Niacinamide', icon:'🧪', benefit:'Barrier repair', origin:'B3 Vitamin', desc:'Minimises pores, reduces redness, fades pigmentation, regulates oil, and strengthens skin barrier.', tags:['Pores','Barrier'] },
  { name:'Green Tea Extract', icon:'🍵', benefit:'Antioxidant', origin:'Japan', desc:'Rich in EGCG. Calms inflammation, combats free radicals, and reduces redness from environmental stress.', tags:['Antioxidant','Soothing'] }
];

window.PRODUCTS = PRODUCTS;
window.BLOG_POSTS = BLOG_POSTS;
window.ROUTINES = ROUTINES;
window.INGREDIENTS_DATA = INGREDIENTS_DATA;